sudo:   required
services:
    - docker


before-install:
    -  docker build -t daveharry/docker-react -f Dockerfile.dev .

script:
    -   docker run -e CI=true daveharry/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-918079683318"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY


