sudo:   required
services:
    - docker


before-install:
    -  docker build -t daveharry/docker-react -f Dockerfile.dev .

script:
    -   docker run -e CI=true daveharry/docker-react npm run test

